language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/WalmartLabs/ELFoundation.git ../ELFoundation
script:
   - xctool -project ELDispatch.xcodeproj -scheme ELDispatch -sdk iphonesimulator build test
