language: objective-c
osx_image: xcode8

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
script:
  - xctool -project ELDispatch.xcodeproj -scheme ELDispatch -sdk iphonesimulator build test
