language: objective-c
osx_image: xcode8

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
script:
  - xcodebuild -project ELDispatch.xcodeproj -scheme ELDispatch -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
