language: objective-c
osx_image: xcode8

install: 
  - carthage update --no-build
script:
  - xcodebuild -project ELDispatch.xcodeproj -scheme ELDispatch -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' CODE_SIGNING_REQUIRED=NO
